blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.urls import path, reverse_lazy

app_name = "blog"
urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.PostListView.as_view(), name='post_list'),
    path('posts/<id>', views.post_detail, name='post_title'),
    path('posts/<id_post>/comment', views.comment_post, name='comment_post'),
    path('ticket/', views.ticket, name="ticket"),
    path('postuser/', views.post_user, name='postuser'),
    path('search/', views.search_post, name="search_post"),
    path('profile/', views.profile, name="profile"),
    path('profile/addpost', views.add_post, name="add_post"),
    path('profile/addpost/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('password-change/', auth_view.PasswordChangeView.as_view(
        template_name='user_information/password_change_form.html',
        success_url='/blog/password-change/done/'), name='password_change'),
    path('password-change/done/', auth_view.PasswordChangeDoneView.as_view(
        template_name='user_information/password_change_done.html'), name='password_change_done'),
    path('password-reset/', views.password_reset_request_view, name='password_reset'),
    path('password-reset/done/', views.password_reset_done_view, name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('password-reset/complete/', views.password_reset_complete_view, name='password_reset_complete'),
    path('register/', views.register, name="register"),
    path('account/edit/', views.edit_account, name='edit_account'),
    path('user_profile/<str:username>/', views.show_profile, name='user_profile'),
    path('all_comments', views.all_comment, name='all_comments'),
    path('post/', views.PostListView.as_view(), name='post_list'),

]

sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ("انتقاد", "انتقاد"),
        ("پیشنهاد", "پیشنهاد"),
        ("گزارش", "گزارش"),
    )
    massage = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField(max_length=250, required=True)
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, required=True)

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if phone:
            if phone.isnumeric():
                if phone.startswith("09"):
                    return phone
                else:
                    raise forms.ValidationError("اول شماره تلفن اشتباه است!")
            else:
                raise forms.ValidationError("شماره تلفن عددی نیست!")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "body"]


# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['title', 'description', 'slug', 'publish', 'status', 'reading_time']


class PostUser(forms.Form):
    class Status:
        DRAFT = 'DR'
        PUBLISHED = 'PU'
        REJECTED = 'RJ'
        CHOICES = [
            (DRAFT, 'Draft'),
            (PUBLISHED, 'Published'),
            (REJECTED, 'Rejected'),
        ]

    title = forms.CharField(max_length=250)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))
    slug = forms.SlugField(max_length=250)
    status = forms.ChoiceField(choices=Status.CHOICES, initial=Status.DRAFT)
    reading_time = forms.IntegerField(min_value=1)

    def clean_title(self):
        title = self.cleaned_data["title"]
        if title:
            if len(title) <= 250:
                return title
            else:
                raise forms.ValidationError("Title must be less than 250 characters.")

    def clean_reading_time(self):
        reading_time = self.cleaned_data["reading_time"]
        if reading_time:
            if reading_time >= 1:
                return reading_time
            else:
                raise forms.ValidationError("Study time must be greater than 0.")


class SearchPost(forms.Form):
    query = forms.CharField()


class CreatedPost(forms.ModelForm):
    image1 = forms.ImageField(required=False, label="image1")
    image2 = forms.ImageField(required=False, label="image2")

    class Meta:
        model = Post
        fields = ["title", "description", "reading_time"]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField()


class SetNewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned = super().clean()
        if cleaned.get('new_password') != cleaned.get('confirm_password'):
            raise forms.ValidationError("Passwords do not match")
        return cleaned


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label="password")
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label="repeat password")

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['bio', 'birth', 'photo', 'job']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .forms import PasswordResetRequestForm, SetNewPasswordForm
from django.shortcuts import render
from django.contrib.auth.tokens import default_token_generator as token_generator
import random

token_generator = PasswordResetTokenGenerator()


def index(request):
    posts = Post.objects.filter(status=Post.Status.PUBLISHED).all()
    posts_random = random.choice(posts)
    return render(request, 'blog/home_page.html', {'posts_top': posts_random})


# def post_list(request, category=None):
#     if category is not None:
#         posts = Post.objects.filter(category = category)
#     else:
#         posts = Post.objects.filter(status=Post.Status.PUBLISHED).all()
#     paginator = Paginator(posts, 3)
#     page_number = request.GET.get('page', 1)
#     try:
#         posts = paginator.page(page_number)
#     except EmptyPage:
#         posts = paginator.page(paginator.num_pages)
#     except PageNotAnInteger:
#         posts = paginator.page(1)
#     context = {
#         'category': category,
#         'posts': posts
#     }
#     return render(request, "blog/listPost.html", context)


class PostListView(ListView):
    queryset = Post.objects.filter(status=Post.Status.PUBLISHED)
    paginate_by = 6
    context_object_name = 'Posts'
    template_name = "blog/listPost.html"


def post_detail(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comment = post.comments.filter(activ=True)
    context = {
        "post": post,
        "form": form,
        "comment": comment
    }
    return render(request, "blog/postdetail.html", context)


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            ticket_obj = Ticket.objects.create()
            ticket_obj.massage = cd["massage"]
            ticket_obj.name = cd["name"]
            ticket_obj.email = cd["email"]
            ticket_obj.phone = cd["phone"]
            ticket_obj.subject = cd["subject"]
            ticket_obj.save()
            return redirect("blog:ticket")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def comment_post(request, id_post):
    post = get_object_or_404(Post, id=id_post, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        "post": post,
        "form": form,
        "comment": comment
    }
    return render(request, "forms/comment.html", context)


def post_user(request):
    default_user = User.objects.get(id=1)
    if request.method == "POST":
        form = PostUser(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            add_post = Post.objects.create(
                author=default_user,
                title=cd["title"],
                description=cd["description"],
                slug=cd["slug"],
                status=cd["status"],
                reading_time=cd["reading_time"]
            )
            add_post.save()
            return redirect("blog:index")
    else:
        form = PostUser()
        return render(request, "forms/user_post.html", {"form": form})


def search_post(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchPost(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Post.objects.filter(status=Post.Status.PUBLISHED) \
                .annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1)
            results2 = Post.objects.filter(status=Post.Status.PUBLISHED) \
                .annotate(similarity=TrigramSimilarity('description', query)).filter(similarity__gt=0.1)
            results3 = Image.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1)
            results4 = Image.objects.annotate(similarity=TrigramSimilarity('description', query)).filter(
                similarity__gt=0.1)
            results = (results1 | results2).order_by('-similarity')
            results_image = (results3 | results4).order_by('-similarity')

    context = {
        'query': query,
        'results': results,
        'results_image': results_image
    }
    return render(request, "blog/search_post.html", context)


@login_required
def profile(request):
    user = request.user
    posts = Post.objects.filter(status=Post.Status.PUBLISHED).filter(author=user)
    context = {
        'user': user,
        'posts': posts
    }
    return render(request, "blog/profile.html", context)


def add_post(request):
    if request.method == "POST":
        form = CreatedPost(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_field=form.cleaned_data["image1"], post=post)
            Image.objects.create(image_field=form.cleaned_data["image2"], post=post)
            post.save()
            return redirect('blog:profile')
    else:
        form = CreatedPost()
    return render(request, "forms/created_post.html", {"form": form})


def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    else:
        return render(request, "forms/post-delete.html", {"post": post})


def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect("blog:profile")


def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatedPost(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            image1 = form.cleaned_data.get("image1")
            image2 = form.cleaned_data.get("image2")

            if image1:
                Image.objects.create(image_field=image1, post=post)
            if image2:
                Image.objects.create(image_field=image2, post=post)

            return redirect('blog:profile')
    else:
        form = CreatedPost(instance=post)

    return render(request, "forms/created_post.html", {"form": form, "post": post})


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd["username"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile')
                else:
                    return HttpResponse("Your account is disabled")
            else:
                return HttpResponse("You are not logged in")
    else:
        form = LoginForm()
    return render(request, "user_information/login.html", {"form": form})


def user_logout(request):
    logout(request)
    return redirect('blog:index')


def password_reset_request_view(request):
    if request.method == 'POST':
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = None
            if user:
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = token_generator.make_token(user)
                reset_path = reverse('blog:password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
                reset_url = request.build_absolute_uri(reset_path)
                send_mail(
                    'Password Reset',
                    f'Click here to reset your password: {reset_url}',
                    'from@example.com',
                    [email],
                    fail_silently=False,
                )
            return redirect('blog:password_reset_done')
    else:
        form = PasswordResetRequestForm()
    return render(request, 'partials/password_reset_form.html', {'form': form})


def password_reset_confirm_view(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (User.DoesNotExist, ValueError, TypeError):
        user = None

    validlink = False
    if user is not None and token_generator.check_token(user, token):
        validlink = True
        if request.method == 'POST':
            form = SetNewPasswordForm(request.POST)
            if form.is_valid():
                user.set_password(form.cleaned_data['new_password'])
                user.save()
                return redirect('blog:password_reset_complete')
        else:

blog/templates/partials/active_user_post.html
<div>
    <p>user active: {{ user_active.username }}</p>
    <p>number post: {{ user_active.post_count }}</p>
    {% for post in latest_posts %}
        <p><a href="{{post.get_absolut_url}}">{{post.title}}</a></p>
    {% endfor %}
</div>

blog/templates/partials/footer.html
<footer class="mega-footer">
  <div class="footer-container">
    <div class="footer-section about">
      <h3>About Me</h3>
      <p>I'm a passionate developer writing about programming languages, frameworks, and tips to boost your coding journey.</p>
    </div>

    <div class="footer-section contact">
      <h3>Contact</h3>
      <p>📞 <a href="tel:+989938231429">+98 993 823 1429</a></p>
      <p>📧 <a href="mailto:daniyal.karvnd@gmail.com">daniyal.karvnd@gmail.com</a></p>
    </div>

    <div class="footer-section links">
      <h3>Quick Links</h3>
      <ul>
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        <li><a href="{% url 'blog:post_list' %}">Posts</a></li>
        <li><a href="{% url 'blog:ticket' %}">Ticket</a></li>
        <li><a href="{% url 'blog:profile' %}">Profile</a></li>
      </ul>
    </div>

    <div class="footer-section social" id="Contact_us">
      <h3>Follow Me</h3>
      <a href="https://wa.me/989938231429" target="_blank"><img src="https://cdn-icons-png.flaticon.com/512/124/124034.png" alt="WhatsApp" /></a>
      <a href="https://t.me/@ِِDaniyal_it" target="_blank"><img src="https://cdn-icons-png.flaticon.com/512/2111/2111646.png" alt="Telegram" /></a>
      <a href="https://github.com/YourGitHubUsername" target="_blank"><img src="https://cdn-icons-png.flaticon.com/512/733/733553.png" alt="GitHub" /></a>
    </div>

    <div class="footer-section newsletter">
      <h3>Subscribe</h3>
      <form>
        <input type="email" placeholder="Your Email..." >
        <button type="submit">Subscribe</button>
      </form>
    </div>
  </div>

  <div class="footer-bottom">
    <p>© 2025 All rights reserved | Example of work</p>
  </div>
</footer>

<script>
  const footer = document.querySelector('.mega-footer');
  const bgColors = [
    "#1a1a1a",    // Dark Gray
    "#0d1b2a",    // Navy Blue
    "#3c096c",    // Dark Purple
    "#2c3e50",    // Slate
    "#4b0082",    // Indigo
    "#550000",    // Dark Red
    "#003d00",    // Dark Green
    "#000066"     // Deep Blue
  ];
  let index = 0;

  setInterval(() => {
    footer.style.backgroundColor = bgColors[index];
    index = (index + 1) % bgColors.length;
  }, 5000);
</script>

blog/templates/partials/header.html
<nav class="navbar">
    {% csrf_token %}
    <a class="a_nav" href="{% url 'blog:index' %}">Home</a>
    <a class="a_nav" href="{% url 'blog:post_list' %}">Posts</a>
    <a class="a_nav" href="{% url 'blog:ticket' %}">Ticket</a>
    {% if user.is_authenticated %}
        <a class="a_nav" href="{% url 'blog:profile' %}">Profile</a>
        <a class="a_nav" href="{% url 'blog:edit_account' %}">Edit_Info</a>
    {% endif %}


    {% if user.is_authenticated %}
        <span class="a_nav user-name" style="margin-left: 900px;">Hello, {{ user.username }}</span>
        <a class="a_nav" href="{% url 'blog:logout' %}">Logout</a>
    {% else %}
        <a class="a_nav" href="{% url 'blog:login' %}" style="margin-left:1160px">Login</a>
        <a class="a_nav" href="{% url 'blog:register' %}">Signup</a>
    {% endif %}
</nav>
<br>

blog/templates/partials/last_post.html
<div>
    <h2>last posts</h2>
    {% for post in l_post %}
        <p><a href="{{ post.get_absolut_url }}"> {{post.title}}</a></p>
    {% endfor %}
</div>

blog/templates/partials/navigation.html
<p>navigation</p>

blog/templates/partials/paginators.html
<div id="style_paginators">
  {% if page.has_previous %}
    <a href="?page={{page.previous_page_number}}" class="Previous_Next"> Previous </a>
  {% endif %}
  Page {{page.number}} of {{page.paginator.num_pages}}
  {% if page.has_next %}
  <a href="?page={{page.next_page_number}}" class="Previous_Next"> Next </a>
  {% endif %}
</div>

blog/templates/partials/password_reset_complete.html
{% extends 'parent/base.html' %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<div class="success-container">
  <h3>Reset Password</h3>
  <p>Password changed successfully.</p>
  <p><a href="{% url 'blog:login' %}">Login</a></p>

  <!-- confetti elements -->
  <div class="confetti-piece" style="--left: 5%; --delay: 0s; --duration: 4s; --color: #e74c3c;"></div>
  <div class="confetti-piece" style="--left: 15%; --delay: 1s; --duration: 5.2s; --color: #f1c40f;"></div>
  <div class="confetti-piece" style="--left: 25%; --delay: 0.7s; --duration: 4.8s; --color: #3498db;"></div>
  <div class="confetti-piece" style="--left: 35%; --delay: 0.3s; --duration: 6.1s; --color: #2ecc71;"></div>
  <div class="confetti-piece" style="--left: 45%; --delay: 1.2s; --duration: 5.5s; --color: #9b59b6;"></div>
  <div class="confetti-piece" style="--left: 55%; --delay: 0.4s; --duration: 4.4s; --color: #e67e22;"></div>
  <div class="confetti-piece" style="--left: 62%; --delay: 0.9s; --duration: 5.8s; --color: #1abc9c;"></div>
  <div class="confetti-piece" style="--left: 70%; --delay: 0.2s; --duration: 6.3s; --color: #34495e;"></div>
  <div class="confetti-piece" style="--left: 78%; --delay: 1.1s; --duration: 5.1s; --color: #8e44ad;"></div>
  <div class="confetti-piece" style="--left: 85%; --delay: 0.6s; --duration: 4.6s; --color: #27ae60;"></div>
  <div class="confetti-piece" style="--left: 92%; --delay: 1.3s; --duration: 5.3s; --color: #c0392b;"></div>
  <div class="confetti-piece" style="--left: 98%; --delay: 0.8s; --duration: 6s; --color: #2980b9;"></div>
</div>
{% endblock %}

blog/templates/partials/password_reset_confirm.html
{% extends 'parent/base.html' %}

{% block content %}
  {% if validlink %}
  <div class="reset-password-container">
    <h3>Reset Password</h3>
    <p>Please enter your password twice.</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <ul>
            <li>Your password cannot be similar to any other personal information you have.</li>
            <li>Your password must be at least 8 characters long.</li>
            <li>Your password cannot be a common password.</li>
            <li>Your password cannot be all numbers.</li>
        </ul>
        <input type="submit" value="Reset Password">
    </form>
  </div>
  {% else %}
    <div class="invalid-link-message">
      The link is invalid
    </div>
  {% endif %}
{% endblock %}

blog/templates/partials/password_reset_done.html
{% extends 'parent/base.html' %}

{% block content %}
<div class="confirmation-container">
  <h3>Reset Password</h3>
  <p>A password change link has been sent to you. Please check your email.</p>
</div>
{% endblock %}

blog/templates/partials/password_reset_email.html
<p>Hello my friend</p>
<p>You have requested a password change</p>
{{email}}
<p>If you do not want to change your password, close the page and ignore this message.</p>
<a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}">
    Reset your password
</a>

blog/templates/partials/password_reset_form.html
{% extends 'parent/base.html' %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<div class="reset-container">
  <h3>Reset Password</h3>
  <p>Please Enter password.</p>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Reset Password" class="submit-btn">
  </form>
</div>
{% endblock %}

blog/templates/partials/slider.html
<div class="slider">
  <div class="slide"><img src="https://picsum.photos/id/1011/900/400" alt=""></div>
  <div class="slide"><img src="https://picsum.photos/id/1015/900/400" alt=""></div>
  <div class="slide"><img src="https://picsum.photos/id/1025/900/400" alt=""></div>
</div>

<style>
  .slider {
    position: relative;
    width: 100%;
    max-width: 900px;
    height: 400px;
    margin: 40px auto;
    overflow: hidden;
    border-radius: 15px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.4);
  }

  .slide {
    display: none;
    position: absolute;
    width: 100%;
    height: 100%;
  }

  .slide img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
  }
</style>

<script>
  let slides = document.querySelectorAll('.slide');
  let index = 0;

  function showSlide(i) {
    slides.forEach(slide => slide.style.display = 'none');
    slides[i].style.display = 'block';
  }

  function nextSlide() {
    index = (index + 1) % slides.length;
    showSlide(index);
  }

  showSlide(index);
  setInterval(nextSlide, 4000);
</script>