blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.urls import path, reverse_lazy

app_name = "blog"
urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.PostListView.as_view(), name='post_list'),
    path('posts/<id>', views.post_detail, name='post_title'),
    path('posts/<id_post>/comment', views.comment_post, name='comment_post'),
    path('ticket/', views.ticket, name="ticket"),
    path('postuser/', views.post_user, name='postuser'),
    path('search/', views.search_post, name="search_post"),
    path('profile/', views.profile, name="profile"),
    path('profile/addpost', views.add_post, name="add_post"),
    path('profile/addpost/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('password-change/', auth_view.PasswordChangeView.as_view(
        template_name='user_information/password_change_form.html',
        success_url='/blog/password-change/done/'), name='password_change'),
    path('password-change/done/', auth_view.PasswordChangeDoneView.as_view(
        template_name='user_information/password_change_done.html'), name='password_change_done'),
    path('password-reset/', views.password_reset_request_view, name='password_reset'),
    path('password-reset/done/', views.password_reset_done_view, name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('password-reset/complete/', views.password_reset_complete_view, name='password_reset_complete'),
    path('register/', views.register, name="register"),
    path('account/edit/', views.edit_account, name='edit_account'),
    path('user_profile/<str:username>/', views.show_profile, name='user_profile'),
    path('all_comments', views.all_comment, name='all_comments'),
    path('post/', views.PostListView.as_view(), name='post_list'),

]

sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ("انتقاد", "انتقاد"),
        ("پیشنهاد", "پیشنهاد"),
        ("گزارش", "گزارش"),
    )
    massage = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField(max_length=250, required=True)
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, required=True)

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if phone:
            if phone.isnumeric():
                if phone.startswith("09"):
                    return phone
                else:
                    raise forms.ValidationError("اول شماره تلفن اشتباه است!")
            else:
                raise forms.ValidationError("شماره تلفن عددی نیست!")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "body"]


# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['title', 'description', 'slug', 'publish', 'status', 'reading_time']


class PostUser(forms.Form):
    class Status:
        DRAFT = 'DR'
        PUBLISHED = 'PU'
        REJECTED = 'RJ'
        CHOICES = [
            (DRAFT, 'Draft'),
            (PUBLISHED, 'Published'),
            (REJECTED, 'Rejected'),
        ]

    title = forms.CharField(max_length=250)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))
    slug = forms.SlugField(max_length=250)
    status = forms.ChoiceField(choices=Status.CHOICES, initial=Status.DRAFT)
    reading_time = forms.IntegerField(min_value=1)

    def clean_title(self):
        title = self.cleaned_data["title"]
        if title:
            if len(title) <= 250:
                return title
            else:
                raise forms.ValidationError("Title must be less than 250 characters.")

    def clean_reading_time(self):
        reading_time = self.cleaned_data["reading_time"]
        if reading_time:
            if reading_time >= 1:
                return reading_time
            else:
                raise forms.ValidationError("Study time must be greater than 0.")


class SearchPost(forms.Form):
    query = forms.CharField()


class CreatedPost(forms.ModelForm):
    image1 = forms.ImageField(required=False, label="image1")
    image2 = forms.ImageField(required=False, label="image2")

    class Meta:
        model = Post
        fields = ["title", "description", "reading_time"]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField()


class SetNewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned = super().clean()
        if cleaned.get('new_password') != cleaned.get('confirm_password'):
            raise forms.ValidationError("Passwords do not match")
        return cleaned


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label="password")
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label="repeat password")

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['bio', 'birth', 'photo', 'job']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from .forms import PasswordResetRequestForm, SetNewPasswordForm
from django.shortcuts import render
from django.contrib.auth.tokens import default_token_generator as token_generator
import random

token_generator = PasswordResetTokenGenerator()


def index(request):
    posts = Post.objects.filter(status=Post.Status.PUBLISHED).all()
    posts_random = random.choice(posts)
    return render(request, 'blog/home_page.html', {'posts_top': posts_random})


# def post_list(request, category=None):
#     if category is not None:
#         posts = Post.objects.filter(category = category)
#     else:
#         posts = Post.objects.filter(status=Post.Status.PUBLISHED).all()
#     paginator = Paginator(posts, 3)
#     page_number = request.GET.get('page', 1)
#     try:
#         posts = paginator.page(page_number)
#     except EmptyPage:
#         posts = paginator.page(paginator.num_pages)
#     except PageNotAnInteger:
#         posts = paginator.page(1)
#     context = {
#         'category': category,
#         'posts': posts
#     }
#     return render(request, "blog/listPost.html", context)


class PostListView(ListView):
    queryset = Post.objects.filter(status=Post.Status.PUBLISHED)
    paginate_by = 6
    context_object_name = 'Posts'
    template_name = "blog/listPost.html"


def post_detail(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comment = post.comments.filter(activ=True)
    context = {
        "post": post,
        "form": form,
        "comment": comment
    }
    return render(request, "blog/postdetail.html", context)


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            ticket_obj = Ticket.objects.create()
            ticket_obj.massage = cd["massage"]
            ticket_obj.name = cd["name"]
            ticket_obj.email = cd["email"]
            ticket_obj.phone = cd["phone"]
            ticket_obj.subject = cd["subject"]
            ticket_obj.save()
            return redirect("blog:ticket")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def comment_post(request, id_post):
    post = get_object_or_404(Post, id=id_post, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        "post": post,
        "form": form,
        "comment": comment
    }
    return render(request, "forms/comment.html", context)


def post_user(request):
    default_user = User.objects.get(id=1)
    if request.method == "POST":
        form = PostUser(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            add_post = Post.objects.create(
                author=default_user,
                title=cd["title"],
                description=cd["description"],
                slug=cd["slug"],
                status=cd["status"],
                reading_time=cd["reading_time"]
            )
            add_post.save()
            return redirect("blog:index")
    else:
        form = PostUser()
        return render(request, "forms/user_post.html", {"form": form})


def search_post(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchPost(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Post.objects.filter(status=Post.Status.PUBLISHED) \
                .annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1)
            results2 = Post.objects.filter(status=Post.Status.PUBLISHED) \
                .annotate(similarity=TrigramSimilarity('description', query)).filter(similarity__gt=0.1)
            results3 = Image.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1)
            results4 = Image.objects.annotate(similarity=TrigramSimilarity('description', query)).filter(
                similarity__gt=0.1)
            results = (results1 | results2).order_by('-similarity')
            results_image = (results3 | results4).order_by('-similarity')

    context = {
        'query': query,
        'results': results,
        'results_image': results_image
    }
    return render(request, "blog/search_post.html", context)


@login_required
def profile(request):
    user = request.user
    posts = Post.objects.filter(status=Post.Status.PUBLISHED).filter(author=user)
    context = {
        'user': user,
        'posts': posts
    }
    return render(request, "blog/profile.html", context)


def add_post(request):
    if request.method == "POST":
        form = CreatedPost(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_field=form.cleaned_data["image1"], post=post)
            Image.objects.create(image_field=form.cleaned_data["image2"], post=post)
            post.save()
            return redirect('blog:profile')
    else:
        form = CreatedPost()
    return render(request, "forms/created_post.html", {"form": form})


def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    else:
        return render(request, "forms/post-delete.html", {"post": post})


def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect("blog:profile")


def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatedPost(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            image1 = form.cleaned_data.get("image1")
            image2 = form.cleaned_data.get("image2")

            if image1:
                Image.objects.create(image_field=image1, post=post)
            if image2:
                Image.objects.create(image_field=image2, post=post)

            return redirect('blog:profile')
    else:
        form = CreatedPost(instance=post)

    return render(request, "forms/created_post.html", {"form": form, "post": post})


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd["username"], password=cd["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile')
                else:
                    return HttpResponse("Your account is disabled")
            else:
                return HttpResponse("You are not logged in")
    else:
        form = LoginForm()
    return render(request, "user_information/login.html", {"form": form})


def user_logout(request):
    logout(request)
    return redirect('blog:index')


def password_reset_request_view(request):
    if request.method == 'POST':
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = None
            if user:
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = token_generator.make_token(user)
                reset_path = reverse('blog:password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
                reset_url = request.build_absolute_uri(reset_path)
                send_mail(
                    'Password Reset',
                    f'Click here to reset your password: {reset_url}',
                    'from@example.com',
                    [email],
                    fail_silently=False,
                )
            return redirect('blog:password_reset_done')
    else:
        form = PasswordResetRequestForm()
    return render(request, 'partials/password_reset_form.html', {'form': form})


def password_reset_confirm_view(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (User.DoesNotExist, ValueError, TypeError):
        user = None

    validlink = False
    if user is not None and token_generator.check_token(user, token):
        validlink = True
        if request.method == 'POST':
            form = SetNewPasswordForm(request.POST)
            if form.is_valid():
                user.set_password(form.cleaned_data['new_password'])
                user.save()
                return redirect('blog:password_reset_complete')
        else:

blog/templates/blog/home_page.html
{% extends 'parent/base.html' %}
{% load blog_tags %}
{% load jformat %}
{% block title %} HOME {% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% block content %}
<form method="get" action="{% url 'blog:search_post' %}" class="search-form">
    <input type="text" name="query" placeholder="Enter the desired text..." class="search-input">
    <input type="submit" value="Search" class="search-button">
</form>
<br>
{% include 'partials/slider.html' %}
<br>
<div class="card">
    <h2>Statistics from the site</h2>
    <p>Number of posts: {% title_post %}</p>
    <p>Number of comments: {% title_comment %}</p>
    <p>Last post date: {% last_post %}</p>
    <p>Minimum time to study: {% min_reading_time %}</p>
    <p>Maximum time to study: {% max_reading_time %}</p>
</div>

<div class="card">
    <h2>Active users</h2>
    {% active_user %}
</div>

<div class="card">
    <h2>Top posts</h2>
    {% top_post as top %}
    <p style="color:black">{% for posts_top in top %}</p>
        <p><a href="{{ posts_top.get_absolut_url }}"  class="black-link">{{ posts_top.title }}</a></p>
    {% endfor %}
</div>

<div class="card">
    <h2>Post Random</h2>
    <a href="{{ posts_top.get_absolut_url }}" class="black-link">{{ posts_top.title }}</a>
</div>

{% endblock %}

</body>
</html>

blog/templates/blog/listPost.html
{% extends 'parent/base.html' %}
{% block title %} Post List {% endblock %}

{% block content %}
    <form method="get" action="{% url 'blog:search_post' %}" class="search-form">
    <input type="text" name="query" placeholder="Enter the desired text..." class="search-input">
    <input type="submit" value="Search" class="search-button">
    </form>
    {% include 'partials/slider.html' %}
    <div class="post-list-header">
        <h1 class="post-list-title">Post List</h1>
    </div>

    <ol class="post-list" style="--length: {{ Posts|length }}" role="list">
        {% for post in Posts %}
        <li class="post-item" style="--i: {{ forloop.counter }}">
            <h3 class="post-item-title">
                <a href="{{ post.get_absolut_url }}" class="post-item-link">{{ post.title }}</a>
            </h3>
            <p class="post-item-description">{{ post.description|truncatewords:2 }}</p>

            {% with post.images.first as first_image %}
                {% if first_image and first_image.image_field and first_image.image_field.url %}
                    <img class="post-item-image" src="{{ first_image.image_field.url }}" alt="{{ first_image.title }}">
                {% endif %}
            {% endwith %}
        </li>
        {% endfor %}
    </ol>

    {% include "partials/paginators.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/postdetail.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load blog_tags %}
{% block title %} post details {% endblock %}

{% block content %}
<div class="glass_post_wrapper">
    <h2 class="glass_post_title">{{ post.title }}</h2>
<div class="glass_post_content">

    {% with post.images.all|first as image_first %}
        {% if image_first and image_first.image_field and image_first.image_field.url %}
            <img class="glass_main_image" src="{{ image_first.image_field.url }}" alt="{{ image_first.title }}">
        {% endif %}
    {% endwith %}

    <p class="glass_post_description">{{ post.description | sensor }}</p>

<div class="glass_post_gallery-slider">
    {% for img in post.images.all|slice:"1:" %}
        {% if img.image_field and img.image_field.url %}
            <a href="#img{{ img.id }}">
                <img class="glass_sub_image" src="{{ img.image_field.url }}" alt="{{ img.title }}">
            </a>

            <!-- لایت‌باکس استاتیک با anchor -->
            <div class="lightbox" id="img{{ img.id }}">
                <a href="#" class="lightbox-close">&times;</a>
                <img class="lightbox-img" src="{{ img.image_field.url }}" alt="{{ img.title }}">
            </div>
        {% endif %}
    {% endfor %}
</div>


</div>

    <hr>
    <div class="glass_post_meta">
        <p><a href="{% url 'blog:user_profile' post.author.username %}" class="black-link">Login to profile({{post.author}})</a></p>
        <p>Author: {{ post.author }}</p>
        <p>Date: {{ post.updated | jformat:'%Y/%m/%d' }}</p>
        <p>Time: {{ post.updated | jformat:'%H:%M' }}</p>
        <p>Reading Time: {{ post.reading_time }}</p>
    </div>
</div>

<hr>

<h2 class="glass_comment_title">{{ comment.count }} Comments</h2>

<div class="glass_comment_list">
    {% for cm in comment %}
        <div class="glass_comment_item">
            <p class="glass_comment_author">Name: {{ cm.name }}</p>
            <p class="glass_comment_text">Comment: {{ cm.body|linebreaks }}</p>
        </div>
        <hr>
    {% empty %}
        <p class="glass_no_comment">No Comments</p>
    {% endfor %}
</div>

<form method="post" action="{% url 'blog:comment_post' post.id %}">
    {% csrf_token %}
    <div class="glass_comment_form">
        <div class="glass_form_left">
            <label for="name" class="glass_label">Name:</label>
            <input type="text" name="name" placeholder="Enter your name"
                   class="glass_input"
                   {% if form.name.value %} value="{{ form.name.value }}" {% endif %}>
            <input type="submit" value="Add Comment" class="glass_submit_btn">
        </div>

        <div class="glass_form_right">
            <label for="body" class="glass_label">Comment:</label>
            <textarea name="body" class="glass_textarea" placeholder="Write your comment here..."></textarea>
        </div>
    </div>
</form>
{% endblock %}

blog/templates/blog/profile.html
{% extends 'parent/base.html' %}
{% block title %}Profile{% endblock %}

{% block content %}
  <style>
    .table-container {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      min-height: 70vh; /* تغییر بده به 100vh اگه بخوای کامل وسط صفحه باشه */
    }

    table.styled-table {
      width: 80%;
      border-collapse: collapse;
      margin-top: 20px;
      font-size: 1rem;
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      overflow: hidden;
    }

    .styled-table th, .styled-table td {
      padding: 12px 15px;
      border: 1px solid #ddd;
      text-align: center;
      transition: all 0.3s ease;
    }

    .styled-table th {
      background-color: #4CAF50;
      color: white;
    }

    .styled-table tr:nth-child(even) {
      background-color: #f9f9f9;
    }

    .styled-table tr:hover {
      background-color: #e0f7fa;
      transform: scale(1.02);
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    }

    .action-link {
      color: #007bff;
      text-decoration: none;
      font-weight: bold;
      transition: color 0.3s ease;
    }

    .action-link:hover {
      text-decoration: underline;
      color: #0056b3;
    }






  </style>
  <p><a href="{% url 'blog:add_post' %}" class="profile">Add Post</a></p>



  <div class="table-container">
    <p style="font-size: 1.1rem;">User: {{ user }}</p>

    <table class="styled-table">
      <tr>
        <th>Row</th>
        <th>Observations</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      {% for post in posts %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td><a class="action-link" href="{{ post.get_absolut_url }}">{{ post.title }}</a></td>
          <td><a class="action-link" href="{% url 'blog:edit_post' post.id %}">Edit</a></td>
          <td><a class="action-link" href="{% url 'blog:delete_post' post.id %}">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
      <p><a href="{% url 'blog:password_change' %}" class="ripple-btn" >change password</a></p>
      <p><a href="{% url 'blog:all_comments' %}" class="ripple-btn" >all comment</a></p>
  </div>
{% include "partials/paginators.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/search_post.html
{% extends 'parent/base.html' %}

{% block title %} search post {% endblock %}

<html lang="fa">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% block content %}

        {% if query %}
            <h4>Number of posts: {{results.count}}</h4>
        {% endif %}
        <h4>لینک های مربوط به پست ها</h4>
        {% for post in results %}
        <ul>
            <li><a href="{{ post.get_absolut_url }}">{{ post.title }}</a></li>
            <li><p>{{ post.description|truncatewords:10 }}</p></li>
            {% empty %}
            <li><p>هیچ پستی یافت نشد</p></li>
        </ul>
        {% endfor %}
        <h4>لینک های مربوط به تصاویر پست ها</h4>
        {% for post_image in results_image %}
            <ul>
                <li><a href="{{ post_image.post.get_absolut_url }}">{{ post_image.title }}</a></li>
                <li><p>{{ post_image.description|truncatewords:5 }}</p></li>

            {% empty %}
                <li><p>هیچ پستی یافت نشد</p></li>
            </ul>
        {% endfor %}

    {% endblock %}
</body>
</html>