blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.urls import path, reverse_lazy

app_name = "blog"
urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.PostListView.as_view(), name='post_list'),
    path('posts/<id>', views.post_detail, name='post_title'),
    path('posts/<id_post>/comment', views.comment_post, name='comment_post'),
    path('ticket/', views.ticket, name="ticket"),
    path('postuser/', views.post_user, name='postuser'),
    path('search/', views.search_post, name="search_post"),
    path('profile/', views.profile, name="profile"),
    path('profile/addpost', views.add_post, name="add_post"),
    path('profile/addpost/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('password-change/', auth_view.PasswordChangeView.as_view(
        template_name='user_information/password_change_form.html',
        success_url='/blog/password-change/done/'), name='password_change'),
    path('password-change/done/', auth_view.PasswordChangeDoneView.as_view(
        template_name='user_information/password_change_done.html'), name='password_change_done'),
    path('password-reset/', views.password_reset_request_view, name='password_reset'),
    path('password-reset/done/', views.password_reset_done_view, name='password_reset_done'),
    path('reset-password-confirm/<uidb64>/<token>/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('password-reset/complete/', views.password_reset_complete_view, name='password_reset_complete'),
    path('register/', views.register, name="register"),
    path('account/edit/', views.edit_account, name='edit_account'),
    path('user_profile/<str:username>/', views.show_profile, name='user_profile'),
    path('all_comments', views.all_comment, name='all_comments'),
    path('post/', views.PostListView.as_view(), name='post_list'),

]

sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django_jalali.db import models as jmodels
from django_resized import ResizedImageField
from django.db.models.signals import post_delete
from django.dispatch import receiver
import os
from django.template.defaultfilters import slugify

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        PUBLISHED = 'PU', 'Published'
        REJECTED = 'RJ', 'Rejected'

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_posts', verbose_name="نویسنده")
    title = models.CharField(max_length=250, verbose_name="عنوان")
    description = models.TextField(verbose_name="توضیحات")
    slug = models.SlugField(max_length=250, verbose_name="اسلاگ")
    publish = jmodels.jDateTimeField(default=timezone.now, verbose_name="تاریخ انتشار")
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name="وضعیت")
    reading_time = models.PositiveIntegerField(verbose_name="زمان مطالعه")
    objects = jmodels.jManager()
    Published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]
        verbose_name = "پست ها"
        verbose_name_plural = "پست ها"

    def __str__(self):
        return self.title

    def get_absolut_url(self):
        return reverse('blog:post_title', args=[self.id])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Ticket(models.Model):
    massage = models.TextField(verbose_name="پیغام")
    name = models.CharField(max_length=250, verbose_name="نام")
    email = models.EmailField(max_length=250, verbose_name="ایمیل")
    phone = models.CharField(max_length=11, verbose_name="شماره تماس")
    subject = models.CharField(max_length=250, verbose_name="نوع درخواست")
    objects = models.Manager()

    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"

    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments", verbose_name="پست")
    name = models.CharField(max_length=250, verbose_name="نام")
    body = models.TextField(verbose_name="متن کامنت")
    created = jmodels.jDateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")
    updated = jmodels.jDateTimeField(auto_now=True, verbose_name="تاریخ بروز رسانی")
    activ = models.BooleanField(default=False, verbose_name="وضعیت")
    objects = models.Manager()

    class Meta:
        ordering = ["-created"]
        indexes = [
            models.Index(fields=["-created"])
        ]
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"

    def __str__(self):
        return self.name


def get_image_upload_to(instance, filename):
    current_year = timezone.now().year
    return f'post_images/{current_year}/{filename}'


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images", verbose_name="پست")
    image_field = ResizedImageField(upload_to=get_image_upload_to, verbose_name="تصویر", size=[500, 500],
                                    crop=['middle', 'center'], quality=75)
    title = models.CharField(max_length=250, verbose_name="عنوان", null=True, blank=True)
    description = models.TextField(verbose_name="توضیحات", null=True, blank=True)
    created = jmodels.jDateTimeField(auto_now_add=True)
    objects = models.Manager()

    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"])
        ]
        verbose_name = "تصویر"
        verbose_name_plural = "تصویر ها"

    def __str__(self):
        if self.title:
            return self.title
        else:
            file_name = os.path.basename(self.image_field.name)
            return file_name


@receiver(post_delete, sender=Image)
def delete_image_file(sender, instance, **kwargs):
    if instance.image_field:
        instance.image_field.delete(save=False)


@receiver(post_delete, sender=Post)
def delete_post_images(sender, instance, **kwargs):
    for image in instance.images.all():
        if image.image_field:
            image.image_field.delete(save=False)


def get_image_upload_to_account(instance, filename):
    current_year = timezone.now().year
    return f'Account/{current_year}/{filename}'


class Account(models.Model):
    user = models.OneToOneField(User, related_name='account', on_delete=models.CASCADE)
    bio = models.TextField(verbose_name="توضیحات", blank=True, null=True)
    birth = jmodels.jDateField(verbose_name="تاریخ تولد", blank=True, null=True)
    photo = ResizedImageField(upload_to=get_image_upload_to_account, verbose_name="تصویر", size=[500, 500], crop=['middle', 'center'], quality=75)
    job = models.CharField(max_length=250, verbose_name="شغل", blank=True, null=True)
    objects = models.Manager()

    class Meta:
        verbose_name = "اکانت"
        verbose_name_plural = "اکانت ها"

    def __str__(self):
        return self.user.username

blog/forms.py
from django import forms
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ("انتقاد", "انتقاد"),
        ("پیشنهاد", "پیشنهاد"),
        ("گزارش", "گزارش"),
    )
    massage = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField(max_length=250, required=True)
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, required=True)

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if phone:
            if phone.isnumeric():
                if phone.startswith("09"):
                    return phone
                else:
                    raise forms.ValidationError("اول شماره تلفن اشتباه است!")
            else:
                raise forms.ValidationError("شماره تلفن عددی نیست!")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "body"]


# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['title', 'description', 'slug', 'publish', 'status', 'reading_time']


class PostUser(forms.Form):
    class Status:
        DRAFT = 'DR'
        PUBLISHED = 'PU'
        REJECTED = 'RJ'
        CHOICES = [
            (DRAFT, 'Draft'),
            (PUBLISHED, 'Published'),
            (REJECTED, 'Rejected'),
        ]

    title = forms.CharField(max_length=250)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))
    slug = forms.SlugField(max_length=250)
    status = forms.ChoiceField(choices=Status.CHOICES, initial=Status.DRAFT)
    reading_time = forms.IntegerField(min_value=1)

    def clean_title(self):
        title = self.cleaned_data["title"]
        if title:
            if len(title) <= 250:
                return title
            else:
                raise forms.ValidationError("Title must be less than 250 characters.")

    def clean_reading_time(self):
        reading_time = self.cleaned_data["reading_time"]
        if reading_time:
            if reading_time >= 1:
                return reading_time
            else:
                raise forms.ValidationError("Study time must be greater than 0.")


class SearchPost(forms.Form):
    query = forms.CharField()


class CreatedPost(forms.ModelForm):
    image1 = forms.ImageField(required=False, label="image1")
    image2 = forms.ImageField(required=False, label="image2")

    class Meta:
        model = Post
        fields = ["title", "description", "reading_time"]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField()


class SetNewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned = super().clean()
        if cleaned.get('new_password') != cleaned.get('confirm_password'):
            raise forms.ValidationError("Passwords do not match")
        return cleaned


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label="password")
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label="repeat password")

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['bio', 'birth', 'photo', 'job']

blog/templates/user_information/author_profile.html
{% extends 'parent/base.html' %}
{% block title %} User Profile {% endblock %}

{% block content %}
<style>
    .profile-container {
        max-width: 400px;
        margin: 40px auto;
        padding: 20px;
        border-radius: 16px;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        background: linear-gradient(to bottom right, #ffffff, #f0f0f0);
        text-align: center;
        animation: fadeIn 1s ease-in-out;
    }

    .profile-photo {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        object-fit: cover;
        transition: transform 0.3s ease;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);
        margin-bottom: 20px;
    }

    .profile-photo:hover {
        transform: scale(1.1) rotate(2deg);
    }

    .profile-info p {
        font-size: 16px;
        margin: 8px 0;
        color: #333;
    }

    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(30px); }
        to { opacity: 1; transform: translateY(0); }
    }
</style>

<div class="profile-container">
    <img src="{{ account.photo.url }}" alt="User photo" class="profile-photo">
    <div class="profile-info">
        <p><strong>User:</strong> {{ user.username }}</p>
        <p><strong>First Name:</strong> {{ user.first_name }}</p>
        <p><strong>Last Name:</strong> {{ user.last_name }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Job:</strong> {{ account.job }}</p>
        <p><strong>Bio:</strong> {{ account.bio }}</p>
        <p><strong>Posts:</strong></p>
        {% for post in posts %}
            <a href="{{post.get_absolut_url}}" class="black-link">{{post.title}}</a>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/user_information/congratulations.html
{% extends 'parent/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <div class="register-success-box">
    <h3 class="welcome-title">Welcome, {{ user }}</h3>
    <p class="success-message">Your registration was successful.</p>
    <a href="{% url 'blog:login' %}" class="login-button">Login</a>
  </div>
{% endblock %}

blog/templates/user_information/edit_information.html
{% extends 'parent/base.html' %}

{% block title %}Edit Account{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data" class="form-card">
  {% csrf_token %}

  <h2>User Information</h2>
  <div class="form-group">
    <label for="id_first_name">First Name</label>
    {{ user_form.first_name }}
  </div>
  <div class="form-group">
    <label for="id_last_name">Last Name</label>
    {{ user_form.last_name }}
  </div>
  <div class="form-group">
    <label for="id_email">Email</label>
    {{ user_form.email }}
  </div>

  <hr>

  <h2>Profile Information</h2>
  <div class="form-group">
    <label for="id_bio">Bio</label>
    {{ account_form.bio }}
  </div>
  <div class="form-group">
    <label for="id_birth">Date of Birth</label>
    {{ account_form.birth }}
  </div>
  <div class="form-group">
    <label for="id_job">Job</label>
    {{ account_form.job }}
  </div>
  <div class="form-group">
    <label for="id_photo">Profile Photo</label>
    <p>{{ account_form.photo }}</p>
  </div>

  <button type="submit" class="submit-btn">Save Changes</button>
</form>

{% endblock %}

blog/templates/user_information/login.html
{% extends 'parent/base.html' %}
{% block title %} Login {% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
{% block content %}
<div class="login-container">
  <div class="bubbles-wrapper">
    <h2 class="login-title">Login</h2>
    <div class="bubble bubble1"></div>
    <div class="bubble bubble2"></div>
    <div class="bubble bubble3"></div>
    <div class="bubble bubble4"></div>
    <div class="bubble bubble5"></div>
  </div>

  <form method="POST" class="login-form">
    {% csrf_token %}
    <label for="username" class="form-label">Username:</label>
    <input type="text" placeholder="Username" name="username" class="form-input">

    <label for="password" class="form-label">Password:</label>
    <input type="password" placeholder="Password" name="password" class="form-input">
    <input type="submit" value="Login" class="submit-btn">
  </form>
  <a href="{% url 'blog:password_reset' %}" id="rest_password">You have successfully changed your password.</a>
</div>
{% endblock %}

</body>
</html>

blog/templates/user_information/password_change_done.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Change Password Done{% endblock %}

{% block content %}

<div class="underwater-container">
    <!-- حباب‌ها -->
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>
    <div class="bubble"></div>

    <!-- باکس پیام -->
    <div class="message-box">
        <h3>Password change successful.</h3>
        <a href="{% url 'blog:index' %}">Back to Home</a>
    </div>
</div>

{% endblock %}

blog/templates/user_information/password_change_form.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Change Password{% endblock %}

{% block content %}
<div class="content-wrapper">

  <!-- پس‌زمینه انیمیشنی فقط پشت فرم -->
  <div class="glowing-background">
    <div class="glow-circle circle1"></div>
    <div class="glow-circle circle2"></div>
    <div class="glow-circle circle3"></div>
    <div class="glow-circle circle4"></div>
  </div>

  <!-- فرم تغییر رمز -->
  <div class="form-box">
    <h3 class="form-title">🔒 Change Password</h3>
    <p class="form-desc">Enter your old and new password</p>

    <form method="post" novalidate>
      {% csrf_token %}

      {% if form.old_password %}
        <div class="form-group">
          <label for="{{ form.old_password.id_for_label }}">Old Password</label>
          <input type="password" name="{{ form.old_password.name }}" id="{{ form.old_password.id_for_label }}" class="form-input" required>
          {{ form.old_password.errors }}
        </div>
      {% endif %}

      <div class="password-help">
        <ul>
          <li>Your password cannot be similar to any other personal information you have.</li>
          <li>Your password must be at least 8 characters long.</li>
          <li>Your password cannot be a common password.</li>
          <li>Your password cannot be all numbers.</li>
        </ul>
      </div>

      {% if form.new_password1 %}
        <div class="form-group">
          <label for="{{ form.new_password1.id_for_label }}">New Password</label>
          <input type="password" name="{{ form.new_password1.name }}" id="{{ form.new_password1.id_for_label }}" class="form-input" required>
          {{ form.new_password1.errors }}
        </div>
      {% endif %}

      {% if form.new_password2 %}
        <div class="form-group">
          <label for="{{ form.new_password2.id_for_label }}">Confirm New Password</label>
          <input type="password" name="{{ form.new_password2.name }}" id="{{ form.new_password2.id_for_label }}" class="form-input" required>
          {{ form.new_password2.errors }}
        </div>
      {% endif %}

      <button type="submit" class="submit-button">Change Password</button>
    </form>
  </div>

</div>
{% endblock %}

blog/templates/user_information/register.html
{% extends 'parent/base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
  <div class="register-container">
    <h2 class="register-title">Register</h2>
    <form method="POST" class="register-form">
      {% csrf_token %}

      <div class="form-group">
        {{ form.username.label_tag }}
        {{ form.username }}
        {% if form.username.errors %}
          <div class="error-message">{{ form.username.errors }}</div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.first_name.label_tag }}
        {{ form.first_name }}
        {% if form.first_name.errors %}
          <div class="error-message">{{ form.first_name.errors }}</div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.last_name.label_tag }}
        {{ form.last_name }}
        {% if form.last_name.errors %}
          <div class="error-message">{{ form.last_name.errors }}</div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.email.label_tag }}
        {{ form.email }}
        {% if form.email.errors %}
          <div class="error-message">{{ form.email.errors }}</div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.password.label_tag }}
        {{ form.password }}
        {% if form.password.errors %}
          <div class="error-message">{{ form.password.errors }}</div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.password2.label_tag }}
        {{ form.password2 }}
        {% if form.password2.errors %}
          <div class="error-message">{{ form.password2.errors }}</div>
        {% endif %}
      </div>

      <input type="submit" value="Register" class="submit-button">
    </form>
  </div>
{% endblock %}